-- MySQL Script generated by MySQL Workbench
-- ven. 24 juin 2022 11:12:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sharebnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharebnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharebnb` ;
USE `sharebnb` ;

-- -----------------------------------------------------
-- Table `sharebnb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `sharebnb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(1000) NOT NULL,
  `type` ENUM("location", "event") NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `project_cost` INT NOT NULL DEFAULT 0,
  `share_link` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_group_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `sharebnb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`expedition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`expedition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `expedition_name` VARCHAR(105) NOT NULL,
  `localisation` VARCHAR(45) NULL,
  `total_cost` INT NOT NULL DEFAULT 0,
  `is_closed` TINYINT NOT NULL DEFAULT 0,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_expedition_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_expedition_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `sharebnb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`possible_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`possible_location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `price` INT NULL,
  `is_booked` TINYINT NOT NULL DEFAULT 0,
  `expedition_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `localisation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `expedition_id`, `project_id`),
  INDEX `fk_possible_location_expedition1_idx` (`expedition_id` ASC, `project_id` ASC) VISIBLE,
  CONSTRAINT `fk_possible_location_expedition1`
    FOREIGN KEY (`expedition_id` , `project_id`)
    REFERENCES `sharebnb`.`expedition` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`user_has_group` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`, `project_id`),
  INDEX `fk_user_has_group_group1_idx` (`group_id` ASC, `project_id` ASC) VISIBLE,
  INDEX `fk_user_has_group_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sharebnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id` , `project_id`)
    REFERENCES `sharebnb`.`group` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`user_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`user_has_project` (
  `project_role` ENUM("master", "contributor", "viewer") NOT NULL DEFAULT 'viewer',
  `budget_part` INT NOT NULL DEFAULT 1,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_user_has_project_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_user_has_project_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sharebnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `sharebnb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`user_vote_for_possible_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`user_vote_for_possible_location` (
  `is_voted` TINYINT NOT NULL DEFAULT 0,
  `comment` TEXT(1000) NULL,
  `user_id` INT NOT NULL,
  `possible_location_id` INT NOT NULL,
  `expedition_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `possible_location_id`, `expedition_id`, `project_id`),
  INDEX `fk_user_has_possible_location_possible_location1_idx` (`possible_location_id` ASC, `expedition_id` ASC, `project_id` ASC) VISIBLE,
  INDEX `fk_user_has_possible_location_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_possible_location_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sharebnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_possible_location_possible_location1`
    FOREIGN KEY (`possible_location_id` , `expedition_id` , `project_id`)
    REFERENCES `sharebnb`.`possible_location` (`id` , `expedition_id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`other_expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`other_expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expense_name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL DEFAULT 0,
  `payer_id` INT NOT NULL,
  `payer_name` VARCHAR(45) NOT NULL,
  `is_resolve` TINYINT NOT NULL DEFAULT 0,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_other_expense_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_other_expense_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `sharebnb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebnb`.`todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebnb`.`todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(105) NOT NULL,
  `description` TEXT(1000) NULL,
  `owner_id` INT NOT NULL,
  `creation_date` INT NOT NULL,
  `project_id` INT NOT NULL,
  `group_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_todo_group1_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_todo_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_todo_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `sharebnb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `sharebnb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sharebnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
